version: "3"
services:
  mssqlserver:
    image: "mcr.microsoft.com/mssql/server"
    container_name: mssqlserver
    environment:
      SA_PASSWORD: "Password_123456"
      ACCEPT_EULA: "Y"
    ports:
      - 1433:1433
